_welcome:
    pattern:  /
    defaults: { _controller: AcmeOrderBundle:Order:index }

_order:
    resource: "@AcmeOrderBundle/Controller/OrderController.php"
    type:     annotation
    prefix:   /order

_sync:
    resource: "@AcmeSyncBundle/Controller/SyncController.php"
    type:     annotation
    prefix:   /sync